services:
  - type: web
    name: msystem
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn msystem.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: msystem-db
          property: connectionString

databases:
  - name: msystem-db
    plan: free
